INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','ID','EXT-015942-00001',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astname','PROY-WATER DSS',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astsum','Summary of Asset #1',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','asttech','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','asttype','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astsoc','Everis Argentina',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astanun','Aerospacial',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astun','BPO',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astbdu','BD Aeroepacial',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astdate',NULL,'2018-07-13 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astemail','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astadcon','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astteccon','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST56','astavl','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','ID','2',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astname','Inversión - Reporting',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astsum','An asset is a resource with economic value that an individual, corporation or country owns or controls with the expectation that it will provide a future benefit. Assets are reported on a company''s balance sheet and are bought or created to increase a fi',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','asttech','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','asttype','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astsoc','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astanun','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astun','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astbdu','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astemail','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astadcon','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astteccon','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('AST61','astavl','',NULL,NULL,NULL);
